//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionManager.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogicResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogicResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollectionManager.Logic.Properties.LogicResources", typeof(LogicResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object of type &apos;{0}&apos; and name &apos;{1}&apos; could not be created. Reason: {2}..
        /// </summary>
        internal static string CreateOperation_Failure {
            get {
                return ResourceManager.GetString("CreateOperation_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object of type &apos;{0}&apos; and name &apos;{1}&apos; was created successfully with ID &apos;{2}&apos;..
        /// </summary>
        internal static string CreateOperation_Success {
            get {
                return ResourceManager.GetString("CreateOperation_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object(s) matching criteria &apos;{0}&apos; could not be displayed. Reason: {1}..
        /// </summary>
        internal static string DisplayOperation_Failure {
            get {
                return ResourceManager.GetString("DisplayOperation_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object(s) matching criteria &apos;{0}&apos; was/were displayed successfully..
        /// </summary>
        internal static string DisplayOperation_Success {
            get {
                return ResourceManager.GetString("DisplayOperation_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object with ID &apos;{0}&apos; could not be removed. Reason: {1}..
        /// </summary>
        internal static string RemoveOperation_Failure {
            get {
                return ResourceManager.GetString("RemoveOperation_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object with ID &apos;{0}&apos; was removed successfully..
        /// </summary>
        internal static string RemoveOperation_Success {
            get {
                return ResourceManager.GetString("RemoveOperation_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object with ID &apos;{0}&apos; could not be updated. Reason: {1}..
        /// </summary>
        internal static string UpdateOperation_Failure {
            get {
                return ResourceManager.GetString("UpdateOperation_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object with ID &apos;{0}&apos; was updated successfully..
        /// </summary>
        internal static string UpdateOperation_Success {
            get {
                return ResourceManager.GetString("UpdateOperation_Success", resourceCulture);
            }
        }
    }
}
