//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionManager.SQLServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLServerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLServerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollectionManager.SQLServer.Properties.SQLServerResources", typeof(SQLServerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The find operation failed. The object with given ID does not exist..
        /// </summary>
        internal static string OperationFind_Failure {
            get {
                return ResourceManager.GetString("OperationFind_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The find operation succeeded. The object with given ID was found..
        /// </summary>
        internal static string OperationFind_Success {
            get {
                return ResourceManager.GetString("OperationFind_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fetching of all specified entities succeeded..
        /// </summary>
        internal static string OperationGetAll_Failure {
            get {
                return ResourceManager.GetString("OperationGetAll_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fetching of all specified entities failed..
        /// </summary>
        internal static string OperationGetAll_Success {
            get {
                return ResourceManager.GetString("OperationGetAll_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The removing operation failed..
        /// </summary>
        internal static string OperationRemove_Failure {
            get {
                return ResourceManager.GetString("OperationRemove_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The removing operation succeeded..
        /// </summary>
        internal static string OperationRemove_Success {
            get {
                return ResourceManager.GetString("OperationRemove_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saving operation failed. Nothing was changed..
        /// </summary>
        internal static string OperationSaveChanges_Failure {
            get {
                return ResourceManager.GetString("OperationSaveChanges_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saving operation succeeded. Database was changed..
        /// </summary>
        internal static string OperationSaveChanges_Success {
            get {
                return ResourceManager.GetString("OperationSaveChanges_Success", resourceCulture);
            }
        }
    }
}
